"""added csfloat sales

Revision ID: 17b51e5c19bf
Revises: d818868059f6
Create Date: 2025-06-13 03:13:07.554501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b51e5c19bf'
down_revision: Union[str, None] = 'd818868059f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csfloat_sales', 'date',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csfloat_sales', 'date',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
