"""csfloat 2

Revision ID: 428f03b31b82
Revises: 17b51e5c19bf
Create Date: 2025-06-13 03:24:44.218336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '428f03b31b82'
down_revision: Union[str, None] = '17b51e5c19bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csfloat_sales', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'csfloat_sales', 'skin_variants', ['skin_variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'csfloat_sales', type_='foreignkey')
    op.alter_column('csfloat_sales', 'date',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
