"""added csfloat sales

Revision ID: 579840d3ac39
Revises: 763dfcc9f154
Create Date: 2025-06-13 02:23:30.976914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579840d3ac39'
down_revision: Union[str, None] = '763dfcc9f154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csfloat_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skin_variant_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csfloat_sales')
    # ### end Alembic commands ###
