"""added cs2 items

Revision ID: 763dfcc9f154
Revises: 0962ae34e8e7
Create Date: 2025-06-13 01:40:40.371086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763dfcc9f154'
down_revision: Union[str, None] = '0962ae34e8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_weapons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('rental', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rarities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sticker_effects',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sticker_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_events',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tournament_teams',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('weapons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wears',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collectibles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('genuine', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graffiti',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keychains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_kits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('exclusive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weapon_id', sa.String(), nullable=True),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.Column('min_float', sa.Float(), nullable=True),
    sa.Column('max_float', sa.Float(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('stattrak', sa.Boolean(), nullable=True),
    sa.Column('souvenir', sa.Boolean(), nullable=True),
    sa.Column('paint_index', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stickers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('tournament_event_name', sa.String(), nullable=True),
    sa.Column('tournament_team_name', sa.String(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('effect_name', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['effect_name'], ['sticker_effects.name'], ),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.ForeignKeyConstraint(['tournament_event_name'], ['tournament_events.name'], ),
    sa.ForeignKeyConstraint(['tournament_team_name'], ['tournament_teams.name'], ),
    sa.ForeignKeyConstraint(['type_name'], ['sticker_types.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_collections',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'collection_id')
    )
    op.create_table('skin_collections',
    sa.Column('skin_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.PrimaryKeyConstraint('skin_id', 'collection_id')
    )
    op.create_table('skin_crates',
    sa.Column('skin_id', sa.String(), nullable=False),
    sa.Column('crate_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['crate_id'], ['crates.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.PrimaryKeyConstraint('skin_id', 'crate_id')
    )
    op.create_table('skin_variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('skin_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weapon_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.Column('min_float', sa.Float(), nullable=True),
    sa.Column('max_float', sa.Float(), nullable=True),
    sa.Column('wear_id', sa.String(), nullable=True),
    sa.Column('stattrak', sa.Boolean(), nullable=True),
    sa.Column('souvenir', sa.Boolean(), nullable=True),
    sa.Column('paint_index', sa.String(), nullable=True),
    sa.Column('rarity_id', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.Column('legacy_model', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['wear_id'], ['wears.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skin_wears',
    sa.Column('skin_id', sa.String(), nullable=False),
    sa.Column('wear_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.ForeignKeyConstraint(['wear_id'], ['wears.id'], ),
    sa.PrimaryKeyConstraint('skin_id', 'wear_id')
    )
    op.create_table('sticker_crates',
    sa.Column('sticker_id', sa.String(), nullable=False),
    sa.Column('crate_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['crate_id'], ['crates.id'], ),
    sa.ForeignKeyConstraint(['sticker_id'], ['stickers.id'], ),
    sa.PrimaryKeyConstraint('sticker_id', 'crate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sticker_crates')
    op.drop_table('skin_wears')
    op.drop_table('skin_variants')
    op.drop_table('skin_crates')
    op.drop_table('skin_collections')
    op.drop_table('agent_collections')
    op.drop_table('stickers')
    op.drop_table('skins')
    op.drop_table('patches')
    op.drop_table('music_kits')
    op.drop_table('keychains')
    op.drop_table('graffiti')
    op.drop_table('collectibles')
    op.drop_table('agents')
    op.drop_table('wears')
    op.drop_table('weapons')
    op.drop_table('tournament_teams')
    op.drop_table('tournament_events')
    op.drop_table('teams')
    op.drop_table('styles')
    op.drop_table('sticker_types')
    op.drop_table('sticker_effects')
    op.drop_table('rarities')
    op.drop_table('patterns')
    op.drop_table('keys')
    op.drop_table('crates')
    op.drop_table('collections')
    op.drop_table('categories')
    op.drop_table('base_weapons')
    # ### end Alembic commands ###
