"""added csfloat sales

Revision ID: 8d1f1302ed73
Revises: a1e571646621
Create Date: 2025-06-13 02:29:32.699108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1f1302ed73'
down_revision: Union[str, None] = 'a1e571646621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buff163_buy_orders', 'request_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key(None, 'buff163_buy_orders', 'skin_variants', ['skin_variant_id'], ['id'])
    op.alter_column('buff163_listings', 'request_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key(None, 'buff163_listings', 'skin_variants', ['skin_variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buff163_listings', type_='foreignkey')
    op.alter_column('buff163_listings', 'request_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'buff163_buy_orders', type_='foreignkey')
    op.alter_column('buff163_buy_orders', 'request_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
