"""added csgoempire models

Revision ID: 8ea1909a7b88
Revises: 142d9359efd5
Create Date: 2025-06-24 22:39:34.952534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ea1909a7b88'
down_revision: Union[str, None] = '142d9359efd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csgoempire_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skin_variant_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['skin_variant_id'], ['skin_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csgoempire_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skin_variant_id', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skin_variant_id'], ['skin_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csgoempire_sales')
    op.drop_table('csgoempire_listings')
    # ### end Alembic commands ###
