"""added csfloat sales

Revision ID: a1e571646621
Revises: ead1df7778cc
Create Date: 2025-06-13 02:27:59.600100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e571646621'
down_revision: Union[str, None] = 'ead1df7778cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'csfloat_sales', 'skin_variants', ['skin_variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'csfloat_sales', type_='foreignkey')
    # ### end Alembic commands ###
