"""csfloat 3

Revision ID: b379ace3da61
Revises: 428f03b31b82
Create Date: 2025-06-13 03:27:10.239585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b379ace3da61'
down_revision: Union[str, None] = '428f03b31b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csfloat_sales', 'date',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('csfloat_sales', 'date',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
