"""added csfloat sales

Revision ID: d818868059f6
Revises: 8d1f1302ed73
Create Date: 2025-06-13 03:10:01.654373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd818868059f6'
down_revision: Union[str, None] = '8d1f1302ed73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csfloat_sales', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csfloat_sales', 'date')
    # ### end Alembic commands ###
